"""
metrics.py — performance metrics and report printing for binary options backtests.
"""

import pandas as pd
import numpy as np


def breakeven_win_rate(payout_pct: float) -> float:
    """Calculates breakeven win rate needed: p = 1 / (1 + payout_pct)."""
    return 1 / (1 + payout_pct)


def max_drawdown(balances: pd.Series) -> float:
    running_max = balances.cummax()
    drawdown = (balances - running_max) / running_max
    return drawdown.min()


def compute_metrics(trades_df: pd.DataFrame, start_balance: float, payout_pct: float) -> dict:
    if trades_df.empty:
        return {"n_trades": 0, "note": "No trades were generated by this strategy on this data."}

    n = len(trades_df)
    wins = trades_df["win"].sum()
    win_rate = wins / n
    need = breakeven_win_rate(payout_pct)

    final_balance = trades_df["balance_after"].iloc[-1]
    total_return_pct = (final_balance - start_balance) / start_balance

    avg_win = trades_df.loc[trades_df["win"], "pnl"].mean() if wins > 0 else 0.0
    avg_loss = trades_df.loc[~trades_df["win"], "pnl"].mean() if (n - wins) > 0 else 0.0
    expectancy_per_trade = trades_df["pnl"].mean()

    balances = pd.concat([pd.Series([start_balance]), trades_df["balance_after"]], ignore_index=True)
    mdd = max_drawdown(balances)

    gross_win = trades_df.loc[trades_df["win"], "pnl"].sum()
    gross_loss = -trades_df.loc[~trades_df["win"], "pnl"].sum()
    profit_factor = (gross_win / gross_loss) if gross_loss > 0 else float("inf")

    return {
        "n_trades": n,
        "win_rate": round(win_rate, 4),
        "breakeven_win_rate_needed": round(need, 4),
        "edge_vs_breakeven_pct_points": round((win_rate - need) * 100, 2),
        "start_balance": start_balance,
        "final_balance": round(final_balance, 2),
        "total_return_pct": round(total_return_pct * 100, 2),
        "expectancy_per_trade": round(expectancy_per_trade, 4),
        "avg_win": round(avg_win, 4),
        "avg_loss": round(avg_loss, 4),
        "profit_factor": round(profit_factor, 3) if profit_factor != float("inf") else "inf",
        "max_drawdown_pct": round(mdd * 100, 2),
        "account_blown": bool(final_balance <= 0),
    }


def print_report(metrics: dict):
    print("=" * 50)
    print("BACKTEST REPORT")
    print("=" * 50)
    if metrics.get("n_trades", 0) == 0:
        print(metrics.get("note", "No trades."))
        return
    print(f"Trades taken:            {metrics['n_trades']}")
    print(f"Win rate:                {metrics['win_rate']*100:.2f}%")
    print(f"Win rate needed (payout):{metrics['breakeven_win_rate_needed']*100:.2f}%")
    edge = metrics["edge_vs_breakeven_pct_points"]
    verdict = "PROFITABLE EDGE" if edge > 0 else "LOSING (below breakeven)"
    print(f"Edge vs breakeven:        {edge:+.2f} pct points  -> {verdict}")
    print(f"Start balance:            {metrics['start_balance']:.2f}")
    print(f"Final balance:            {metrics['final_balance']:.2f}")
    print(f"Total return:             {metrics['total_return_pct']:+.2f}%")
    print(f"Expectancy / trade:       {metrics['expectancy_per_trade']:+.4f}")
    print(f"Avg win / Avg loss:       {metrics['avg_win']:+.4f} / {metrics['avg_loss']:+.4f}")
    print(f"Profit factor:            {metrics['profit_factor']}")
    print(f"Max drawdown:             {metrics['max_drawdown_pct']:.2f}%")
    if metrics["account_blown"]:
        print("!!! ACCOUNT WENT TO ZERO OR BELOW !!!")
    print("=" * 50)
